from __future__ import annotations

import logging
from typing import Callable

import requests

from mcp_server.models import (
    RiskLevel,
    ValidationExecutionResponse,
    ValidationStatus,
)

logger = logging.getLogger("mcp_server.validator")


PLACEHOLDER_ENDPOINT = ["example.com", "invalid.local"]


def _is_placeholder_endpoint(endpoint: str) -> bool:
    endpoint = endpoint.strip().lower()
    return any(p in endpoint for p in PLACEHOLDER_ENDPOINT)


def safe_execute(
    secret: str,
    endpoint: str,
    execute_validation: Callable[[str, str], ValidationExecutionResponse],
) -> ValidationExecutionResponse:
    """
    Safely delegate validation execution to the MCP validation engine.
    """
    try:
        return execute_validation(secret, endpoint)
    except Exception as exc:
        logger.exception("validator_execution_error endpoint=%s", endpoint)

        return ValidationExecutionResponse(
            status=ValidationStatus.ERROR,
            risk=RiskLevel.LOW,
            reason=str(exc),
        )


def validate_secret(
    secret: str,
    endpoint: str,
    execute_validation: Callable[[str, str], ValidationExecutionResponse],
) -> ValidationExecutionResponse:
    """
    Generic validator that executes validation against a provided endpoint.
    The endpoint is generated by the LLM validation plan.
    """
    normalized_endpoint = endpoint.strip()

    if not normalized_endpoint:
        logger.info("validator_missing_endpoint")
        return ValidationExecutionResponse(
            status=ValidationStatus.UNKNOWN,
            risk=RiskLevel.LOW,
            reason="Missing validation endpoint",
        )

    if _is_placeholder_endpoint(normalized_endpoint):
        logger.info("validator_skipped_placeholder_endpoint endpoint=%s", normalized_endpoint)
        return ValidationExecutionResponse(
            status=ValidationStatus.UNKNOWN,
            risk=RiskLevel.LOW,
            reason="Validation skipped for placeholder endpoint",
        )

    return safe_execute(secret, normalized_endpoint, execute_validation)


def execute_validation(secret: str, endpoint: str) -> ValidationExecutionResponse:
    """
    Default HTTP validation executor.
    Sends the secret as a Bearer token to the validation endpoint.
    """

    if _is_placeholder_endpoint(endpoint):
        logger.info("validator_skipped_placeholder_endpoint endpoint=%s", endpoint)
        return ValidationExecutionResponse(
            status=ValidationStatus.UNKNOWN,
            risk=RiskLevel.LOW,
            reason="Validation skipped for placeholder endpoint",
        )

    headers = {
        "Authorization": f"Bearer {secret}",
        "User-Agent": "mcp-secret-validator",
    }

    try:
        response = requests.get(endpoint, headers=headers, timeout=5)

        if response.status_code == 200:
            return ValidationExecutionResponse(
                status=ValidationStatus.VALID,
                risk=RiskLevel.HIGH,
                reason="Secret is valid and authenticated",
            )

        if response.status_code in {401, 403}:
            return ValidationExecutionResponse(
                status=ValidationStatus.INVALID,
                risk=RiskLevel.LOW,
                reason="Authentication failed",
            )

        return ValidationExecutionResponse(
            status=ValidationStatus.UNKNOWN,
            risk=RiskLevel.MEDIUM,
            reason=f"Unexpected response code {response.status_code}",
        )

    except requests.RequestException as exc:
        logger.exception("validator_http_error endpoint=%s", endpoint)

        return ValidationExecutionResponse(
            status=ValidationStatus.ERROR,
            risk=RiskLevel.LOW,
            reason=str(exc),
        )